export const DEFAULT_SYMBOL = 'BTCUSDT';
export const SYMBOLS = [
  'BTCUSDT',
  'BNBBTC',
  'ETHBTC',
];

/// events
export const SYMBOL_UPDATE = 'SYMBOL_UPDATE';
export const ORDER_UPDATE = 'ORDER_UPDATE';
export const ORDER_LOAD_STATUS_CHANGE = 'ORDER_LOAD_STATUS_CHANGE';
export const WS_DIFF_MESSAGE = 'WS_DIFF_MESSAGE';
export const WS_DIFF_MESSAGE_COLLECT = 'WS_DIFF_MESSAGE_COLLECT';

// BINANCE CONFIG
export const ORDER_LIMIT = 100;
